# Generated by Django 2.2.12 on 2022-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=10)),
                ('numLessons', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('extra', models.CharField(max_length=10)),
            ],
        ),
    ]
