# Generated by Django 4.1.4 on 2022-12-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='lesson',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
