# Generated by Django 4.1.3 on 2022-12-07 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='extra_info',
            field=models.CharField(blank=True, max_length=750, verbose_name='Extra information'),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.PositiveIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], default=7, validators=[django.core.validators.MinValueValidator(2, 'Cannot request lessons for a period shorter than 2 days.'), django.core.validators.MaxValueValidator(14, 'Cannot request lessons for a period longer than 14 days.')], verbose_name='Interval (days)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
