# Generated by Django 4.1.3 on 2022-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='numLessons',
        ),
        migrations.AddField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.CharField(choices=[('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY')], default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='extra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.PositiveIntegerField(),
        ),
    ]
