# Generated by Django 4.1.3 on 2022-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_banktransfer_paid_remove_banktransfer_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
