# Generated by Django 4.1.3 on 2022-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_startdate_lesson_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.PositiveIntegerField(choices=[(1, 'Every week'), (2, 'Every 2 weeks')], default=1),
        ),
    ]
