# Generated by Django 4.1.3 on 2022-11-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
