# Generated by Django 4.1.3 on 2022-11-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_request_numlessons_request_number_of_lessons_and_more'),
        ('lessons', '0003_remove_user_bio'),
    ]

    operations = [
    ]
