# Generated by Django 4.1.3 on 2022-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_request_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], default='MONDAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '1 hour')], default=30, verbose_name='Duration (mins)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(choices=[(1, '1 lesson'), (2, '2 lessons'), (3, '3 lessons'), (4, '4 lessons')], default=1),
        ),
    ]
