# Generated by Django 4.1.3 on 2022-11-25 00:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_merge_20221122_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='extra',
        ),
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='extra_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Extra information'),
        ),
        migrations.AddField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.PositiveIntegerField(choices=[(30, 30), (45, 45), (60, 60)], default=30, verbose_name='Duration (mins)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2, 'Cannot request lessons for a period shorter than 2 days.'), django.core.validators.MaxValueValidator(14, 'Cannot request lessons for a period longer than 14 days.')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
