# Generated by Django 4.1.3 on 2022-12-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_request_availability_alter_request_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvedRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Fulfilled Request',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lessons.request',),
        ),
        migrations.CreateModel(
            name='pendingRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Request',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lessons.request',),
        ),
    ]
