# Generated by Django 4.1.3 on 2022-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_request_extra_request_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=4)),
                ('invoice_number', models.CharField(max_length=3)),
                ('full_invoice_number', models.CharField(max_length=8)),
                ('pay', models.PositiveIntegerField()),
                ('paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_student_id', models.CharField(max_length=10)),
                ('assigned_teacher_id', models.CharField(max_length=10)),
                ('number_of_lessons', models.PositiveIntegerField(default=1)),
                ('week_interval', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
