# Generated by Django 4.1.4 on 2022-12-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_request_availability_alter_request_extra_info_and_more'),
        ('lessons', '0005_approvedrequest_pendingrequest'),
    ]

    operations = [
    ]
