# Generated by Django 4.1.3 on 2022-12-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='invoice_number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
