# Generated by Django 4.1.3 on 2022-12-09 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_merge_20221208_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], default='MONDAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval',
            field=models.PositiveIntegerField(choices=[(1, 'Every week'), (2, 'Every 2 weeks')], default=1, verbose_name='Interval (weeks)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.PositiveIntegerField(choices=[(1, '1 lesson'), (2, '2 lessons'), (3, '3 lessons'), (4, '4 lessons')], default=1),
        ),
    ]
