# Generated by Django 4.1.3 on 2022-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_alter_banktransfer_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="balance", field=models.FloatField(default=0),
        ),
    ]
